[package]
name = "ip_sniffer"
version = "0.2.0"
authors = ["Dilantha Wijesinghe <wdilantha66@gmail.com>"]
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
bpaf = { version = "0.7", features = ["derive", "bright-color"] }
